### ISSUE TITLE
新部署的环境中，访问配置页面报错

### ISSUE THREAD

**Issue by LinuxSuRen** [LinuxSuRen/autotest.platform#13]
java.lang.NullPointerException
        at org.suren.autotest.web.framework.selenium.DriverMapping.getUrl(DriverMapping.java:79)
        at org.suren.autotest.web.framework.selenium.SeleniumEngine.loadDriverFromMapping(SeleniumEngine.java:423)
        at org.suren.autotest.web.framework.selenium.SeleniumEngine.loadDefaultEnginePath(SeleniumEngine.java:398)
        at org.suren.autotest.web.framework.selenium.SeleniumEngine.initConfig(SeleniumEngine.java:110)
        at org.suren.autotest.web.framework.selenium.SeleniumEngine$$FastClassBySpringCGLIB$$655932d8.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:718)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
        at org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:133)
        at org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:121)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:653)
        at org.suren.autotest.web.framework.selenium.SeleniumEngine$$EnhancerBySpringCGLIB$$61cf4f36.initConfig(<generated>)
        at org.suren.autotest.platform.controller.SystemController.edit(SystemController.java:80)

操作系统为英文的windows10

**Comment by LinuxSuRen** [comment]
缺少对win10的配置
